name: rubidya
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_lints: ^2.0.0
  country_pickers: ^2.0.0
  dio: ^5.3.3
  logger: ^1.1.0
  shared_preferences: ^2.0.0
  path_provider: ^2.0.14
  http: any
  image_picker: ^0.8.7+5
  image: ^3.0.1
  share_plus: ^7.2.1
  flutter_otp_text_field: ^1.1.1
  otp_pin_field: ^1.2.2
  otp_text_field: ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/image/
    - assets/svg/
